### ISSUE TITLE
Parts Missing When Opening Files.

### ISSUE THREAD

**Issue by opensourcefan** [MOCBuilderOrg/MOCBuilder#48]
(Ubuntu 12.04 64bit)

I'm having an issue loading files. They open up fine in LDCad but not here. I've tried my own LDraw library as well as the included LDraw library within the MB folder. The issue seems like it can't find the parts as I get many red "X" in the parts section on the right. 

Many models that I try and load are missing parts here and there, some worse than others. This is what happens when I try and load the attached file. As I said it opens up just fine in both LDCad and JBrickBuilder. 

![screenshot from 2015-01-12 14-29-47s](https://cloud.githubusercontent.com/assets/10550038/5950263/b32d7588-a70c-11e4-9a28-aafc54fff6dd.jpg)

**Comment by funface2** [comment]
It looks a case sensitive problem of part names. 
I'll fix it.

**Comment by opensourcefan** [comment]
Appears to be all fixed, great work, thank you!
